#!/usr/bin/env bash

# avahi-daemon checks
function pre_check_avahi(){
  echo -e "\npre Avahi"
  ERRORS=0

  check_if_os_package_exists "avahi"
  evaluate_result $? "  Avahi os package exists"

  check_if_os_package_exists "avahi-utils"
  evaluate_result $? "  Avahi-utils os package exists"

  check_if_process_exists "avahi"
  evaluate_result $? "  Avahi process exists"

  [[ ! -f "/etc/avahi/avahi-daemon.conf.cluster-lab-backup" ]]
  evaluate_result $? "  /etc/avahi/avahi-daemon.conf backup file is absent"

  [[ $(avahi-browse --all --terminate | grep -c 'IPv6') -gt 0 ]]
  evaluate_result $? "  Avahi is using IPv6 addresses"

  [[ $(avahi-browse --all --terminate | grep -c "${VLAN_INTERFACE}") -eq 0 ]]
  evaluate_result $? "  Avahi is not using ${VLAN_INTERFACE}"

  return "$ERRORS"
}

function post_check_avahi(){
  echo -e "\npost Avahi"
  ERRORS=0

  check_if_process_exists "avahi"
  evaluate_result $? "  Avahi process exists"

  [[ -f "/etc/avahi/avahi-daemon.conf.cluster-lab-backup" ]]
  evaluate_result $? "  /etc/avahi/avahi-daemon.conf backup file exists"

  [[ $(avahi-browse --all --terminate | grep -c 'IPv6') -eq 0 ]]
  evaluate_result $? "  Avahi is not using IPv6 addresses"

  [[ $(avahi-browse --all --terminate | grep -c "${VLAN_INTERFACE}") -gt 0 ]]
  evaluate_result $? "  Avahi is using ${VLAN_INTERFACE}"
  avahi-browse --all --terminate | grep -c "${VLAN_INTERFACE}"

  return "$ERRORS"
}

# setup avahi-daemon
function configure_avahi(){
  # create backup file
  if [[ ! -f "/etc/avahi/avahi-daemon.conf.cluster-lab-backup" ]]; then
    cp /etc/avahi/avahi-daemon.conf /etc/avahi/avahi-daemon.conf.cluster-lab-backup
  fi
  # change configuration
  # disable avahi on wlan0 and docker0
  sed -i -e 's/#deny-interfaces=eth1/deny-interfaces=eth1,wlan0,docker0/'  /etc/avahi/avahi-daemon.conf
  # enable avahi on eth0 and ${VLAN_INTERFACE}
  sed -i -e "s/#allow-interfaces=eth0/allow-interfaces=eth0,${VLAN_INTERFACE}/"  /etc/avahi/avahi-daemon.conf
  # disable use of IPv6 addresses
  sed -i -e 's/use-ipv6=yes/use-ipv6=no/' /etc/avahi/avahi-daemon.conf
}

function reset_avahi(){
    if [ -f "/etc/avahi/avahi-daemon.conf.cluster-lab-backup" ]; then
      rm -f /etc/avahi/avahi-daemon.conf
      mv /etc/avahi/avahi-daemon.conf.cluster-lab-backup /etc/avahi/avahi-daemon.conf
    fi
}

# avahi cluser-master.service file
function pre_check_cluster_leader_service(){
  echo -e "\npre cluster_leader"

  [[ ! -f "/etc/avahi/services/cluster-leader.service" ]]
  local errorcode=$?
  evaluate_result $errorcode "  cluster-leader.service is absent"
  return $errorcode
}

function post_check_cluster_leader_service(){
  echo -e "\npost cluster_leader"
  [[ -f "/etc/avahi/services/cluster-leader.service" ]]
  local errorcode=$?
  evaluate_result $errorcode "  cluster-leader.service exists"
  return $errorcode
}

function add_cluster_leader_service(){
cat << EOM > /etc/avahi/services/cluster-leader.service
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">Cluster-Leader=%h</name>
  <service>
    <type>_cluster._tcp</type>
    <port>22</port>
    <txt-record>os-release=hypriot</txt-record>
  </service>
</service-group>
EOM
}

function delete_cluster_leader_service(){
  rm -f /etc/avahi/services/cluster-leader.service
}
