#!/usr/bin/env bash

# Parameter 1 is return value
# Parameter 2 is message
function evaluate_result(){
  if [ "$1" -eq 0 ]; then
    echo -e "\e[32m  [PASS] ${2}\e[0m"
  else
    echo -e "\e[31m  [FAIL] ${2}\e[0m"
    ERROR=1
  fi
}

function exit_with_message_on_error(){
  if [[ ${1} -gt 0 ]]; then
    echo "${2}"
    exit 1
  fi
}

function get_ip_of_interface(){
  local interface=$1
  local all_ip_addresses=$(hostname -I)
  local interface_ip=$(ip a s "$interface")
  for ip_address in $all_ip_addresses; do
      if [[ "$interface_ip" == *"$ip_address"* ]]; then
        echo "$ip_address"
      fi
  done
}

function escape_ip_for_regex(){
  echo "${1//\./\\\.}"
}

function check_if_process_exists() {
  local process="$1"
  pgrep "$process" > /dev/null 2>&1
  return $?
}

function check_if_os_package_exists(){
  package="$1"
  dpkg -l | grep -q -E "^ii\s*${package}"
  return $?
}
